services:
  # Servicio de backend
  backend:
    build:
      context: ./backend
    image: ${DOCKER_REGISTRY_SERVER:-restaurantapp}/backend:latest
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=${JWT_EXPIRATION}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/check-db"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Servicio de frontend
  frontend:
    build:
      context: ./frontend
      args:
        - VITE_AWS_REGION=${VITE_AWS_REGION:-us-east-2}
        - VITE_AWS_ACCESS_KEY_ID=${VITE_AWS_ACCESS_KEY_ID}
        - VITE_AWS_SECRET_ACCESS_KEY=${VITE_AWS_SECRET_ACCESS_KEY}
        - VITE_AWS_BUCKET_NAME=${VITE_AWS_BUCKET_NAME:-restaurant-items-by-danielxxomg}
    image: ${DOCKER_REGISTRY_SERVER:-restaurantapp}/frontend:latest
    restart: always
    environment:
      - VITE_AWS_REGION=${VITE_AWS_REGION:-us-east-2}
      - VITE_AWS_ACCESS_KEY_ID=${VITE_AWS_ACCESS_KEY_ID}
      - VITE_AWS_SECRET_ACCESS_KEY=${VITE_AWS_SECRET_ACCESS_KEY}
      - VITE_AWS_BUCKET_NAME=${VITE_AWS_BUCKET_NAME:-restaurant-items-by-danielxxomg}
    ports:
      - "80:80"
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s